title: MK2Swag
email: hello@mk2swag.com
description: >-
  Celebrating the passion for MK2 Golfs and Jettas, from all around the world.
baseurl: "/"
url: "https://mk2swag.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections_dir: collections

collections:
  stories:
    output: true
    permalink: /stories/:title
    sort_by: date
  
  pages:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  -
    scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
      type: "story"